CREATE TABLE `dphismon` (
  `HMN_CODIGO` char(3) DEFAULT NULL,
  `HMN_FECHA` date DEFAULT NULL,
  `HMN_HORA` char(8) DEFAULT NULL,
  `HMN_VALOR` decimal(19,8) DEFAULT NULL,
  KEY `DPHISMON1` (`HMN_CODIGO`,`HMN_FECHA`),
  KEY `DPHISMON2` (`HMN_CODIGO`,`HMN_FECHA`),
  CONSTRAINT `DPTABMON_DPHISMON` FOREIGN KEY (`HMN_CODIGO`) REFERENCES `dptabmon` (`MON_CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1